"""Run the agent on showcase queries and save real outputs to docs/examples.md.
Needs OPENAI_API_KEY.

    python scripts/make_examples.py            # gpt-5.6-luna
    python scripts/make_examples.py --final    # gpt-5.6-terra (final)
"""

import argparse
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from dotenv import load_dotenv  # noqa: E402

from copilot import config  # noqa: E402
from copilot.agent import ResearchAgent  # noqa: E402

QUERIES = [
    "How did Nike's gross margin change in fiscal 2025, and what did management say caused it?",
    "By what percentage did Lululemon's net income grow in 2024?",
    "Compare the gross margin drivers at Under Armour and Deckers in fiscal 2025.",
    "What was Adidas's revenue in 2024?",
]


def main() -> None:
    """Run the showcase queries and write docs/examples.md."""
    parser = argparse.ArgumentParser()
    parser.add_argument("--final", action="store_true")
    args = parser.parse_args()
    load_dotenv()
    model = config.EVAL_MODEL if args.final else config.DEV_MODEL
    agent = ResearchAgent(model=model)

    parts = [f"# Example queries\n\nGenerated by `scripts/make_examples.py` with `{model}`.\n"]
    for q in QUERIES:
        r = agent.run(q)
        sources = "  ".join(f"[{i}] {s}" for i, s in enumerate(r.sources, start=1)) or "none"
        tools = ", ".join(f"{name} ({n})" for name, n in r.tool_calls.items()) or "none"
        parts.append(
            f"## {q}\n\n```\nAnswer: {r.answer}\nSources: {sources}\nTool calls: {tools}\n"
            f"Fallback triggered: {str(r.fallback_triggered).lower()}\n```\n"
        )
        print(parts[-1])
    out = config.ROOT / "docs" / "examples.md"
    out.write_text("\n".join(parts), encoding="utf-8")
    print(f"Saved {out.relative_to(config.ROOT)}")


if __name__ == "__main__":
    main()
